
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry Resultado;
	private global::Gtk.Entry Numero2;
	private global::Gtk.Entry Numero1;
	private global::Gtk.Label lbNumero1;
	private global::Gtk.Label lbResultado;
	private global::Gtk.Label lbNumero2;
	private global::Gtk.Button BotonMultiplica;
	private global::Gtk.Button botonDivide;
	private global::Gtk.Button BotonResta;
	private global::Gtk.Button BotonSuma;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Resultado = new global::Gtk.Entry ();
		this.Resultado.CanFocus = true;
		this.Resultado.Name = "Resultado";
		this.Resultado.IsEditable = true;
		this.Resultado.InvisibleChar = '●';
		this.fixed1.Add (this.Resultado);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Resultado]));
		w1.X = 166;
		w1.Y = 94;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero2 = new global::Gtk.Entry ();
		this.Numero2.CanFocus = true;
		this.Numero2.Name = "Numero2";
		this.Numero2.IsEditable = true;
		this.Numero2.InvisibleChar = '●';
		this.fixed1.Add (this.Numero2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero2]));
		w2.X = 167;
		w2.Y = 58;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero1 = new global::Gtk.Entry ();
		this.Numero1.CanFocus = true;
		this.Numero1.Name = "Numero1";
		this.Numero1.IsEditable = true;
		this.Numero1.InvisibleChar = '●';
		this.fixed1.Add (this.Numero1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero1]));
		w3.X = 169;
		w3.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumero1 = new global::Gtk.Label ();
		this.lbNumero1.Name = "lbNumero1";
		this.lbNumero1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.lbNumero1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbNumero1]));
		w4.X = 102;
		w4.Y = 27;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbResultado = new global::Gtk.Label ();
		this.lbResultado.Name = "lbResultado";
		this.lbResultado.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lbResultado);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbResultado]));
		w5.X = 101;
		w5.Y = 99;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumero2 = new global::Gtk.Label ();
		this.lbNumero2.Name = "lbNumero2";
		this.lbNumero2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero2");
		this.fixed1.Add (this.lbNumero2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbNumero2]));
		w6.X = 101;
		w6.Y = 62;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BotonMultiplica = new global::Gtk.Button ();
		this.BotonMultiplica.CanFocus = true;
		this.BotonMultiplica.Name = "BotonMultiplica";
		this.BotonMultiplica.UseUnderline = true;
		this.BotonMultiplica.Label = global::Mono.Unix.Catalog.GetString ("MULTIPLICA");
		this.fixed1.Add (this.BotonMultiplica);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BotonMultiplica]));
		w7.X = 288;
		w7.Y = 144;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.botonDivide = new global::Gtk.Button ();
		this.botonDivide.CanFocus = true;
		this.botonDivide.Name = "botonDivide";
		this.botonDivide.UseUnderline = true;
		this.botonDivide.Label = global::Mono.Unix.Catalog.GetString ("DIVIDE");
		this.fixed1.Add (this.botonDivide);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.botonDivide]));
		w8.X = 286;
		w8.Y = 175;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BotonResta = new global::Gtk.Button ();
		this.BotonResta.CanFocus = true;
		this.BotonResta.Name = "BotonResta";
		this.BotonResta.UseUnderline = true;
		this.BotonResta.Label = global::Mono.Unix.Catalog.GetString ("RESTA");
		this.fixed1.Add (this.BotonResta);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BotonResta]));
		w9.X = 285;
		w9.Y = 207;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BotonSuma = new global::Gtk.Button ();
		this.BotonSuma.CanFocus = true;
		this.BotonSuma.Name = "BotonSuma";
		this.BotonSuma.UseUnderline = true;
		this.BotonSuma.Label = global::Mono.Unix.Catalog.GetString ("SUMA");
		this.fixed1.Add (this.BotonSuma);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BotonSuma]));
		w10.X = 286;
		w10.Y = 236;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BotonMultiplica.Clicked += new global::System.EventHandler (this.OnBotonMultiplicaClicked);
		this.botonDivide.Clicked += new global::System.EventHandler (this.OnBotonDivideClicked);
		this.BotonResta.Clicked += new global::System.EventHandler (this.OnBotonRestaClicked);
		this.BotonSuma.Clicked += new global::System.EventHandler (this.OnBotonSumaClicked);
	}
}
